/**
 * /example - server component shell.
 * Handles metadata (title, og, canonical) so search engines index this
 * correctly. All interactive logic lives in ExampleGuideClient.
 */

import { Metadata } from "next"
import ExampleGuideClient from "./ExampleGuideClient"

export const metadata: Metadata = {
  title: "Apple Tone of Voice Guide - Sample | Tone of Voice App",
  description:
    "See what a complete tone of voice guide looks like. Generated by Tone of Voice App from apple.com — not an official Apple document.",
  robots: { index: true, follow: true },
}

export default function ExampleGuidePage() {
  return <ExampleGuideClient />
}
