/**
 * Pre-generated Apple brand voice guide used as the public sample on /example.
 * Generated by Tone of Voice App from apple.com.
 *
 * This is a static fixture — no runtime generation, no auth required.
 * Update the content here if the sample guide needs refreshing.
 *
 * Last reviewed: March 2026
 */

import {
  LayoutTemplate,
  Info,
  HelpCircle,
  Users,
  Megaphone,
  ScrollText,
  ArrowLeftRight,
  BookOpen,
  Eraser,
  Mail,
} from "lucide-react"
import { StyleGuideSection } from "@/lib/content-parser"

export const EXAMPLE_GUIDE_BRAND_NAME = "Apple"
export const EXAMPLE_GUIDE_WEBSITE_URL = "https://apple.com"
export const EXAMPLE_GUIDE_DATE = "March 2026"
export const EXAMPLE_GUIDE_DISCLAIMER =
  "Generated by Tone of Voice App from apple.com · Not an official Apple document"

export const EXAMPLE_GUIDE_SECTIONS: StyleGuideSection[] = [
  {
    id: "cover",
    title: "Cover",
    content: "",
    level: 1,
    isMainSection: true,
    configId: "cover",
    icon: LayoutTemplate,
    minTier: "starter",
  },
  {
    id: "about",
    title: "About Apple",
    content: `Apple designs technology that is intuitive, personal, and beautiful. Since 1976, the company has stood for a single idea: technology should work for people, not the other way around. Every product, every screen, every word reflects that belief.

Apple's voice is an extension of its products. Clean, direct, human. It doesn't oversell. It doesn't shout. It trusts the work to speak for itself.

This guide captures how Apple communicates - the principles behind the words, the rhythm of the sentences, and the things it never says. Use it to write in a way that feels unmistakably Apple: confident without arrogance, simple without being dumb, warm without being casual.`,
    level: 2,
    isMainSection: true,
    configId: "about",
    icon: Info,
    minTier: "starter",
  },
  {
    id: "how-to-use",
    title: "How to Use This Guide",
    content: `Use this guide whenever you write anything in Apple's voice - product descriptions, UI copy, support articles, campaigns, or anything in between. It is here to keep you consistent, clear, and on-brand.

**The fastest test:** Read your copy aloud. If it sounds like a person talking to another person, you are on track. If it sounds like a press release, start again.

**When in doubt, go to the source.** Apple's product pages at apple.com are the best reference for tone, rhythm, and word choice in action. Read them the way you would read good writing - notice what is there and what is not.

**This guide covers:**
- Who Apple is writing for
- The voice qualities that define Apple's communication
- Grammar, punctuation, and style decisions
- Words Apple uses and words it avoids
- How to clean up AI-generated copy so it sounds human

Apply the principles, not just the rules. Good writing understands why.`,
    level: 2,
    isMainSection: true,
    configId: "how-to-use",
    icon: HelpCircle,
    minTier: "starter",
  },
  {
    id: "audience",
    title: "Your Audience",
    content: `Apple's audience is everyone who has ever been frustrated by technology that made them feel stupid.

They are not early adopters chasing specs. They are not developers optimising pipelines. They are curious, creative, busy people who want things to just work - and to feel good while they do.

**What they care about:**
- What it does for them, not how it works inside
- Whether it fits into their life, not whether it fits into a product category
- Feeling capable, not overwhelmed
- Trustworthiness - they have invested in this ecosystem

**What they do not want:**
- To read a manual
- To feel talked down to
- Marketing that assumes they cannot tell the difference between a claim and a fact
- Jargon that signals "this is complicated"

Write for the person who just wants to take better photos. Write for the person who bought an iPhone because their family uses iPhones. Write for the person who does not know what a gigahertz is and does not need to. They are Apple's biggest audience, and they deserve the same quality of communication as everyone else.`,
    level: 2,
    isMainSection: true,
    configId: "audience",
    icon: Users,
    minTier: "starter",
  },
  {
    id: "brand-voice",
    title: "Brand Voice",
    content: `Apple's voice has four qualities. Every piece of writing should embody all of them.

---

### Simple
Apple does not use words to impress. It uses words to communicate. Every word earns its place. If a sentence works without a word, cut the word. If a paragraph works without a sentence, cut the sentence. Simplicity is not the absence of thought - it is the result of it.

### Direct
Get to the point. Lead with what matters. Do not bury the most important thing at the end of a sentence. Do not make people read three paragraphs before they understand what they are reading about. Direct does not mean blunt - it means respectful of the reader's time.

### Human
Write like a person talking to another person. Use contractions. Use "you." Use "we" when Apple is the subject. Avoid passive voice wherever possible. If you would not say it in a conversation, do not write it. Warmth and clarity are not opposites - Apple writing is both.

### Confident
Apple believes its products are exceptional. It does not need to say so. "Stunning," "revolutionary," and "world-class" are claims. Apple shows instead of telling. A confident voice states things plainly and lets the reader draw the conclusion. It does not hedge. It does not need qualifiers.`,
    level: 2,
    isMainSection: true,
    configId: "brand-voice",
    icon: Megaphone,
    minTier: "starter",
  },
  {
    id: "style-rules",
    title: "Style Rules",
    content: `These are the decisions that make Apple's writing consistent and recognisable at a sentence level.

**Voice and person**
- Always use second person ("you") to address the reader directly
- Use "we" when referring to Apple as an entity; never "the company" or third person
- Active voice by default: "iPhone captures stunning photos," not "Stunning photos are captured by iPhone"

**Sentence structure**
- Write short sentences. Then longer ones when you need them. Vary the rhythm deliberately.
- One idea per sentence when clarity is at risk
- Front-load the important information: subject and verb early, qualifiers after

**Punctuation**
- No exclamation marks in product copy - they undercut confidence
- Oxford comma always: "photos, videos, and audio"
- Em dashes sparingly - only when a pause genuinely helps comprehension
- No ellipses in marketing copy; they signal uncertainty

**Capitalisation**
- Sentence case for headings and button labels, not title case (except for proper nouns and product names)
- Product names follow Apple's own capitalisation: iPhone, iPad, MacBook, AirPods, iCloud
- Do not capitalise "app" or "store" unless part of a proper name (App Store, Mac App Store)

**Numbers**
- Spell out numbers one through nine; use numerals for 10 and above
- Use numerals when the number relates to a spec or measurement: "3 cameras," "6-core chip"

**Tone modifiers to avoid**
- "Simply," "easy," "just," "intuitive" - if it is simple, show it; do not claim it
- "Innovative," "cutting-edge," "next-generation" - claims that need proof you are not providing
- "Exciting," "thrilling," "amazing" - Apple does not get excited about itself in public`,
    level: 2,
    isMainSection: true,
    configId: "style-rules",
    icon: ScrollText,
    minTier: "pro",
  },
  {
    id: "examples",
    title: "Before / After",
    content: `Real rewrites showing how to move from generic to Apple.

---

**Product description**

Before: "Introducing our revolutionary new iPhone 15, featuring the most advanced camera system ever created with industry-leading performance capabilities that will transform the way you capture memories."

After: "iPhone 15. The camera in your pocket just got a lot more powerful."

*Why:* The "before" leads with claims. The "after" leads with the product name, then a single direct statement of benefit. No superlatives. No "introducing."

---

**Support copy**

Before: "Our customer support team is available to assist you in resolving any technical issues you may be experiencing with your Apple products and devices."

After: "Need help? We're here." *(Then: one question at a time. Get to the answer fast.)*

*Why:* The "before" is passive, wordy, and corporate. The "after" opens with the reader's situation, then confirms Apple's presence. Short. Human. Direct.

---

**Feature callout**

Before: "With the all-new AirPods Pro, users can enjoy an immersive audio experience featuring state-of-the-art active noise cancellation technology that effectively blocks out unwanted background noise from the surrounding environment."

After: "AirPods Pro. The world disappears. The music doesn't."

*Why:* The "before" explains the technology. The "after" describes the experience. Apple almost always chooses the experience.

---

**Privacy message**

Before: "Apple is committed to protecting user privacy and ensuring that personal data is handled in accordance with our privacy policy and applicable data protection regulations."

After: "Your data is yours. We work hard to keep it that way."

*Why:* The "before" sounds like legal boilerplate. The "after" sounds like a promise from a person. Same commitment, completely different relationship.`,
    level: 2,
    isMainSection: true,
    configId: "examples",
    icon: ArrowLeftRight,
    minTier: "pro",
  },
  {
    id: "word-list",
    title: "Word List",
    content: `**Words Apple uses**

| Use | Why |
|-----|-----|
| You, your, yours | Keeps the reader central |
| Simple, clean, beautiful | Describes without overselling |
| Powerful, fast, capable | Factual, not hyperbolic |
| Designed, built, crafted | Signals intention and care |
| Privacy, security, trust | Core values stated plainly |
| Works, does, makes | Active verbs that show rather than tell |

---

**Words Apple avoids**

| Avoid | Use instead |
|-------|-------------|
| Best, greatest, world-class | Name the specific advantage |
| Revolutionary, game-changing | Describe what changed, not that it changed |
| Innovative, cutting-edge | Show the innovation; let the reader decide |
| Leverage, utilise, synergise | Use, make use of, work together |
| Solution, offering, product suite | The product name |
| Seamless, frictionless | Describe the actual experience |
| Value proposition | What you get |
| Exciting, thrilling, amazing | Name the thing that is exciting |
| Disruptive | Earned description, not self-applied |
| Ecosystem | Works fine in technical contexts; avoid in consumer copy |

---

**A note on adjectives**

Apple uses fewer adjectives than most brands. When it does use them, they are specific and earned. "A 48-megapixel camera" is more Apple than "an incredible camera." The spec is the claim. The word "incredible" adds nothing.`,
    level: 2,
    isMainSection: true,
    configId: "word-list",
    icon: BookOpen,
    minTier: "pro",
  },
  {
    id: "ai-writing-cleanup",
    title: "AI Writing Cleanup",
    content: `AI tends to write the opposite of Apple. Here are the patterns to catch and fix.

---

**Too many adjectives**

AI piles on descriptors because hedging feels safer than committing to a single strong claim. Apple commits.

- AI output: "an incredibly innovative, cutting-edge, state-of-the-art device with groundbreaking capabilities"
- Apple: "a device that does things nothing else can"

**Fix:** Pick one quality. State it plainly. Cut the rest.

---

**Passive voice**

AI defaults to passive because it is grammatically unambiguous. Apple is almost always active.

- AI output: "users are able to take advantage of advanced features that can be accessed through the settings menu"
- Apple: "open Settings and tap your way to more powerful options"

**Fix:** Find the subject. Make it do something. Kill "are able to."

---

**Corporate opener**

AI loves "Introducing..." and "We are excited to announce..." Apple does neither. Product names go first. Benefits go second.

- AI output: "We are thrilled to introduce our latest innovation in personal audio technology"
- Apple: "AirPods Pro." *(then show what they do)*

**Fix:** Delete the opener. Start with the product or the benefit.

---

**Hedging language**

AI qualifies everything to be safe. Apple states things plainly or does not state them at all.

- AI output: "this may potentially help you to somewhat improve your overall productivity"
- Apple: "it works better" *(or just show the result)*

**Fix:** Remove "may," "potentially," "somewhat," "overall," "help to." If you cannot say it directly, you do not know it well enough to say it.

---

**Filler phrases**

AI fills space. Apple does not.

Remove these on sight:
- "In today's fast-paced world..."
- "It's no secret that..."
- "At Apple, we believe..."
- "With that in mind..."
- "Whether you're a [type of user] or a [type of user]..."`,
    level: 2,
    isMainSection: true,
    configId: "ai-writing-cleanup",
    icon: Eraser,
    minTier: "starter",
  },
  {
    id: "contact",
    title: "Questions?",
    content: `If something in this guide is unclear, or you are unsure how to apply it to a specific piece of writing, go to [apple.com](https://apple.com) and read. Product pages, support articles, and campaign copy are all live examples of Apple's voice in action.

Read them the way you would read good writing. Notice the rhythm. Notice what is not there. That gap - the claim not made, the adjective not used, the sentence that stops before it outstays its welcome - is as much a part of Apple's voice as anything in this guide.

**The question to ask before you publish anything:**

Would Apple write it this way?

If you are not sure, it probably means no.`,
    level: 2,
    isMainSection: true,
    configId: "contact",
    icon: Mail,
    minTier: "starter",
  },
]
